//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 08:09:16 PM IST 
//


package com.tsm.ltf.model.MessageHeaderEnrich;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MessageHeaderEnrichRuleIdentifier"/>
 *         &lt;element ref="{}MessageHeaderEnrichValues"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeaderEnrichRuleIdentifier",
    "messageHeaderEnrichValues"
})
@XmlRootElement(name = "MessageHeaderEnrichRule")
public class MessageHeaderEnrichRule {

    @XmlElement(name = "MessageHeaderEnrichRuleIdentifier", required = true)
    protected MessageHeaderEnrichRuleIdentifier messageHeaderEnrichRuleIdentifier;
    @XmlElement(name = "MessageHeaderEnrichValues", required = true)
    protected MessageHeaderEnrichValues messageHeaderEnrichValues;

    /**
     * Gets the value of the messageHeaderEnrichRuleIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderEnrichRuleIdentifier }
     *     
     */
    public MessageHeaderEnrichRuleIdentifier getMessageHeaderEnrichRuleIdentifier() {
        return messageHeaderEnrichRuleIdentifier;
    }

    /**
     * Sets the value of the messageHeaderEnrichRuleIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderEnrichRuleIdentifier }
     *     
     */
    public void setMessageHeaderEnrichRuleIdentifier(MessageHeaderEnrichRuleIdentifier value) {
        this.messageHeaderEnrichRuleIdentifier = value;
    }

    /**
     * Gets the value of the messageHeaderEnrichValues property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderEnrichValues }
     *     
     */
    public MessageHeaderEnrichValues getMessageHeaderEnrichValues() {
        return messageHeaderEnrichValues;
    }

    /**
     * Sets the value of the messageHeaderEnrichValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderEnrichValues }
     *     
     */
    public void setMessageHeaderEnrichValues(MessageHeaderEnrichValues value) {
        this.messageHeaderEnrichValues = value;
    }

}
