//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 08:09:16 PM IST 
//


package com.tsm.ltf.model.MessageHeaderEnrich;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MessageHeaderEnrichRuleIdentifierKey"/>
 *         &lt;element ref="{}MessageHeaderEnrichRuleIdentifierValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeaderEnrichRuleIdentifierKey",
    "messageHeaderEnrichRuleIdentifierValue"
})
@XmlRootElement(name = "MessageHeaderEnrichRuleIdentifier")
public class MessageHeaderEnrichRuleIdentifier {

    @XmlElement(name = "MessageHeaderEnrichRuleIdentifierKey", required = true)
    protected String messageHeaderEnrichRuleIdentifierKey;
    @XmlElement(name = "MessageHeaderEnrichRuleIdentifierValue", required = true)
    protected String messageHeaderEnrichRuleIdentifierValue;

    /**
     * Gets the value of the messageHeaderEnrichRuleIdentifierKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageHeaderEnrichRuleIdentifierKey() {
        return messageHeaderEnrichRuleIdentifierKey;
    }

    /**
     * Sets the value of the messageHeaderEnrichRuleIdentifierKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageHeaderEnrichRuleIdentifierKey(String value) {
        this.messageHeaderEnrichRuleIdentifierKey = value;
    }

    /**
     * Gets the value of the messageHeaderEnrichRuleIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageHeaderEnrichRuleIdentifierValue() {
        return messageHeaderEnrichRuleIdentifierValue;
    }

    /**
     * Sets the value of the messageHeaderEnrichRuleIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageHeaderEnrichRuleIdentifierValue(String value) {
        this.messageHeaderEnrichRuleIdentifierValue = value;
    }

}
