//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 08:09:16 PM IST 
//


package com.tsm.ltf.model.MessageHeaderEnrich;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tsm.ltf.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageHeaderEnrichValue_QNAME = new QName("", "MessageHeaderEnrichValue");
    private final static QName _MessageHeaderEnrichValueKey_QNAME = new QName("", "MessageHeaderEnrichValueKey");
    private final static QName _MessageHeaderEnrichRuleIdentifierKey_QNAME = new QName("", "MessageHeaderEnrichRuleIdentifierKey");
    private final static QName _MessageHeaderEnrichRuleIdentifierValue_QNAME = new QName("", "MessageHeaderEnrichRuleIdentifierValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tsm.ltf.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageHeaderEnrichRule }
     * 
     */
    public MessageHeaderEnrichRule createMessageHeaderEnrichRule() {
        return new MessageHeaderEnrichRule();
    }

    /**
     * Create an instance of {@link MessageHeaderEnrichRuleIdentifier }
     * 
     */
    public MessageHeaderEnrichRuleIdentifier createMessageHeaderEnrichRuleIdentifier() {
        return new MessageHeaderEnrichRuleIdentifier();
    }

    /**
     * Create an instance of {@link MessageHeaderEnrichValues }
     * 
     */
    public MessageHeaderEnrichValues createMessageHeaderEnrichValues() {
        return new MessageHeaderEnrichValues();
    }

    /**
     * Create an instance of {@link MessageHeaderEnrichRules }
     * 
     */
    public MessageHeaderEnrichRules createMessageHeaderEnrichRules() {
        return new MessageHeaderEnrichRules();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageHeaderEnrichValue")
    public JAXBElement<String> createMessageHeaderEnrichValue(String value) {
        return new JAXBElement<String>(_MessageHeaderEnrichValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageHeaderEnrichValueKey")
    public JAXBElement<String> createMessageHeaderEnrichValueKey(String value) {
        return new JAXBElement<String>(_MessageHeaderEnrichValueKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageHeaderEnrichRuleIdentifierKey")
    public JAXBElement<String> createMessageHeaderEnrichRuleIdentifierKey(String value) {
        return new JAXBElement<String>(_MessageHeaderEnrichRuleIdentifierKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageHeaderEnrichRuleIdentifierValue")
    public JAXBElement<String> createMessageHeaderEnrichRuleIdentifierValue(String value) {
        return new JAXBElement<String>(_MessageHeaderEnrichRuleIdentifierValue_QNAME, String.class, null, value);
    }

}
