//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 08:48:32 PM IST 
//


package com.tsm.ltf.model.LTFCommonStructure;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DataConversionInput" maxOccurs="unbounded"/>
 *         &lt;element ref="{}DataConversionOutput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataConversionInput",
    "dataConversionOutput"
})
@XmlRootElement(name = "DataConversion")
public class DataConversion {

    @XmlElement(name = "DataConversionInput", required = true)
    protected List<DataConversionInput> dataConversionInput;
    @XmlElement(name = "DataConversionOutput", required = true)
    protected DataConversionOutput dataConversionOutput;

    /**
     * Gets the value of the dataConversionInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataConversionInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataConversionInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataConversionInput }
     * 
     * 
     */
    public List<DataConversionInput> getDataConversionInput() {
        if (dataConversionInput == null) {
            dataConversionInput = new ArrayList<DataConversionInput>();
        }
        return this.dataConversionInput;
    }

    /**
     * Gets the value of the dataConversionOutput property.
     * 
     * @return
     *     possible object is
     *     {@link DataConversionOutput }
     *     
     */
    public DataConversionOutput getDataConversionOutput() {
        return dataConversionOutput;
    }

    /**
     * Sets the value of the dataConversionOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataConversionOutput }
     *     
     */
    public void setDataConversionOutput(DataConversionOutput value) {
        this.dataConversionOutput = value;
    }

}
