//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 08:48:32 PM IST 
//


package com.tsm.ltf.model.LTFCommonStructure;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tsm.ltf.model.LTFCommonStructure package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SourceValue_QNAME = new QName("", "SourceValue");
    private final static QName _Destination_QNAME = new QName("", "Destination");
    private final static QName _TransformationStyleSheet_QNAME = new QName("", "TransformationStyleSheet");
    private final static QName _TransformationSourceFormatName_QNAME = new QName("", "TransformationSourceFormatName");
    private final static QName _Operation_QNAME = new QName("", "Operation");
    private final static QName _TransformationTargetFormatName_QNAME = new QName("", "TransformationTargetFormatName");
    private final static QName _Delay_QNAME = new QName("", "Delay");
    private final static QName _TimeStamp_QNAME = new QName("", "TimeStamp");
    private final static QName _ConversionKey_QNAME = new QName("", "ConversionKey");
    private final static QName _SourceApplication_QNAME = new QName("", "SourceApplication");
    private final static QName _Payload_QNAME = new QName("", "Payload");
    private final static QName _TransformationServiceName_QNAME = new QName("", "TransformationServiceName");
    private final static QName _CorrelationID_QNAME = new QName("", "CorrelationID");
    private final static QName _MessageType_QNAME = new QName("", "MessageType");
    private final static QName _MessageID_QNAME = new QName("", "MessageID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tsm.ltf.model.LTFCommonStructure
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transformation }
     * 
     */
    public Transformation createTransformation() {
        return new Transformation();
    }

    /**
     * Create an instance of {@link DataConversionOutput }
     * 
     */
    public DataConversionOutput createDataConversionOutput() {
        return new DataConversionOutput();
    }

    /**
     * Create an instance of {@link DataToConvert }
     * 
     */
    public DataToConvert createDataToConvert() {
        return new DataToConvert();
    }

    /**
     * Create an instance of {@link LTFCommonStructure }
     * 
     */
    public LTFCommonStructure createLTFCommonStructure() {
        return new LTFCommonStructure();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link DataConversion }
     * 
     */
    public DataConversion createDataConversion() {
        return new DataConversion();
    }

    /**
     * Create an instance of {@link DataConversionInput }
     * 
     */
    public DataConversionInput createDataConversionInput() {
        return new DataConversionInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SourceValue")
    public JAXBElement<String> createSourceValue(String value) {
        return new JAXBElement<String>(_SourceValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Destination")
    public JAXBElement<String> createDestination(String value) {
        return new JAXBElement<String>(_Destination_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationStyleSheet")
    public JAXBElement<String> createTransformationStyleSheet(String value) {
        return new JAXBElement<String>(_TransformationStyleSheet_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationSourceFormatName")
    public JAXBElement<String> createTransformationSourceFormatName(String value) {
        return new JAXBElement<String>(_TransformationSourceFormatName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Operation")
    public JAXBElement<String> createOperation(String value) {
        return new JAXBElement<String>(_Operation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationTargetFormatName")
    public JAXBElement<String> createTransformationTargetFormatName(String value) {
        return new JAXBElement<String>(_TransformationTargetFormatName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delay")
    public JAXBElement<String> createDelay(String value) {
        return new JAXBElement<String>(_Delay_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeStamp")
    public JAXBElement<String> createTimeStamp(String value) {
        return new JAXBElement<String>(_TimeStamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConversionKey")
    public JAXBElement<String> createConversionKey(String value) {
        return new JAXBElement<String>(_ConversionKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SourceApplication")
    public JAXBElement<String> createSourceApplication(String value) {
        return new JAXBElement<String>(_SourceApplication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Payload")
    public JAXBElement<String> createPayload(String value) {
        return new JAXBElement<String>(_Payload_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationServiceName")
    public JAXBElement<String> createTransformationServiceName(String value) {
        return new JAXBElement<String>(_TransformationServiceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CorrelationID")
    public JAXBElement<String> createCorrelationID(String value) {
        return new JAXBElement<String>(_CorrelationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageType")
    public JAXBElement<String> createMessageType(String value) {
        return new JAXBElement<String>(_MessageType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageID")
    public JAXBElement<String> createMessageID(String value) {
        return new JAXBElement<String>(_MessageID_QNAME, String.class, null, value);
    }

}
