//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 08:48:32 PM IST 
//


package com.tsm.ltf.model.LTFCommonStructure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TransformationServiceName"/>
 *         &lt;element ref="{}TransformationStyleSheet"/>
 *         &lt;element ref="{}TransformationSourceFormatName"/>
 *         &lt;element ref="{}TransformationTargetFormatName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transformationServiceName",
    "transformationStyleSheet",
    "transformationSourceFormatName",
    "transformationTargetFormatName"
})
@XmlRootElement(name = "Transformation")
public class Transformation {

    @XmlElement(name = "TransformationServiceName", required = true)
    protected String transformationServiceName;
    @XmlElement(name = "TransformationStyleSheet", required = true)
    protected String transformationStyleSheet;
    @XmlElement(name = "TransformationSourceFormatName", required = true)
    protected String transformationSourceFormatName;
    @XmlElement(name = "TransformationTargetFormatName", required = true)
    protected String transformationTargetFormatName;

    /**
     * Gets the value of the transformationServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformationServiceName() {
        return transformationServiceName;
    }

    /**
     * Sets the value of the transformationServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformationServiceName(String value) {
        this.transformationServiceName = value;
    }

    /**
     * Gets the value of the transformationStyleSheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformationStyleSheet() {
        return transformationStyleSheet;
    }

    /**
     * Sets the value of the transformationStyleSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformationStyleSheet(String value) {
        this.transformationStyleSheet = value;
    }

    /**
     * Gets the value of the transformationSourceFormatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformationSourceFormatName() {
        return transformationSourceFormatName;
    }

    /**
     * Sets the value of the transformationSourceFormatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformationSourceFormatName(String value) {
        this.transformationSourceFormatName = value;
    }

    /**
     * Gets the value of the transformationTargetFormatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformationTargetFormatName() {
        return transformationTargetFormatName;
    }

    /**
     * Sets the value of the transformationTargetFormatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformationTargetFormatName(String value) {
        this.transformationTargetFormatName = value;
    }

}
